language: php

php:
  - 5.6
  
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

before_install: composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: ~

# we are really only interested if the composer runs through or not
script: composer update --dry-run

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
